# SwiftLint Configuration for Ritmia

included:
  - Ritmia

excluded:
  - Ritmia/Resources
  - ${PWD}/swiftshield-output
  - ${PWD}/DerivedData
  - ${PWD}/.build
  - ${PWD}/Ritmia.xcodeproj
  - ${PWD}/RitmiaTests
  - ${PWD}/RitmiaUITests

# Rules Configuration

opt_in_rules:
  - empty_count
  - empty_string
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - discouraged_object_literal
  - empty_collection_literal
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

disabled_rules:
  - todo
  - trailing_whitespace
  - vertical_whitespace

# Rules Configuration

line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 400
  error: 600

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z

nesting:
  type_level: 2
  statement_level: 5

cyclomatic_complexity:
  warning: 10
  error: 20

# Custom Rules

custom_rules:
  no_print_statements:
    included: ".*\\.swift"
    excluded: ".*Tests.*\\.swift"
    name: "Print Statements"
    regex: "^\\s*print\\("
    message: "Print statements should not be used in production code. Use proper logging instead."
    severity: warning
